project_name: 'geoipupdate'
archives:
  - id: main
    wrap_in_directory: true
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'
      - 'GeoIP.conf'
      - 'GeoIP.conf.md'
      - 'geoipupdate.md'
    format: zip
builds:
  - main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goarch:
      - '386'
      - 'amd64'
    goos:
      - 'windows'
    hooks:
      post: 'make data OS=Windows_NT BUILDDIR=.'
    env:
      - CGO_ENABLED=0
checksum:
  name_template: 'checksums-windows.txt'
release:
  # We can only do one release.
  disable: true
