project_name: 'geoipupdate'
archive:
  wrap_in_directory: true
  files:
    - 'CHANGELOG.md'
    - 'LICENSE-APACHE'
    - 'LICENSE-MIT'
    - 'README.md'
    - 'GeoIP.conf'
    - 'GeoIP.conf.md'
    - 'geoipupdate.md'
  format_overrides:
    - goos: windows
      format: zip
builds:
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goos:
    - 'darwin'
    - 'linux'
  hooks:
    pre: 'make clean BUILDDIR=.'
    post: 'make data BUILDDIR=.'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goos:
    - 'windows'
  hooks:
    pre: 'make clean BUILDDIR=.'
    post: 'make data OS=Windows_NT BUILDDIR=.'
checksum:
  name_template: 'checksums.txt'
