project_name: 'geoipupdate'
archive:
  wrap_in_directory: true
  files:
    - 'CHANGELOG.md'
    - 'LICENSE-APACHE'
    - 'LICENSE-MIT'
    - 'README.md'
    - 'GeoIP.conf'
  format_overrides:
    - goos: windows
      format: zip
builds:
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - 'amd64'
  goos:
    - 'darwin'
  hooks:
    post: 'make data BUILDDIR=dist/darwin_amd64'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - '386'
  goos:
    - 'linux'
  hooks:
    post: 'make data BUILDDIR=dist/linux_386'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - 'amd64'
  goos:
    - 'linux'
  hooks:
    post: 'make data BUILDDIR=dist/linux_amd64'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - '386'
  goos:
    - 'windows'
  hooks:
    post: 'make data OS=Windows_NT BUILDDIR=dist/windows_386'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - 'amd64'
  goos:
    - 'windows'
  hooks:
    post: 'make data OS=Windows_NT BUILDDIR=dist/windows_amd64'
checksum:
  name_template: 'checksums.txt'
nfpm:
  vendor: 'MaxMind, Inc.'
  homepage: https://www.maxmind.com/
  maintainer: 'MaxMind, Inc. <support@maxmind.com>'
  description: Program to perform automatic updates of GeoIP2 and GeoIP Legacy binary databases.
  license: Apache 2.0 or MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
  empty_folders:
  - /usr/share/GeoIP
  files:
    'CHANGELOG.md': '/usr/share/doc/geoipupdate/CHANGELOG.md'
    'LICENSE-APACHE': '/usr/share/doc/geoipupdate/LICENSE-APACHE'
    'LICENSE-MIT': '/usr/share/doc/geoipupdate/LICENSE-MIT'
    'README.md': '/usr/share/doc/geoipupdate/README.md'
    'GeoIP.conf': '/usr/share/doc/geoipupdate/GeoIP.conf'
    'GeoIP.conf.md': '/usr/share/doc/geoipupdate/GeoIP.conf.md'
    'geoipupdate.md': '/usr/share/doc/geoipupdate/geoipupdate.md'
  config_files:
    'GeoIP.conf': '/etc/GeoIP.conf'
