project_name: 'geoipupdate'
archives:
  - id: main
    wrap_in_directory: true
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'
      - 'GeoIP.conf'
      - 'GeoIP.conf.md'
      - 'geoipupdate.md'
builds:
  - main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goarch:
      - '386'
      - 'amd64'
      - 'arm'
      - 'arm64'
    goos:
      - 'darwin'
      - 'linux'
    hooks:
      post: 'make data BUILDDIR=.'
    env:
      - CGO_ENABLED=0
dockers:
  - image_templates:
      - maxmindinc/geoipupdate
    dockerfile: docker/Dockerfile
    extra_files:
      - docker/entry.sh
checksum:
  name_template: 'checksums-darwin-linux.txt'
