project_name: 'geoipupdate'
archives:
  - id: main
    wrap_in_directory: true
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'
      - 'GeoIP.conf'
      - 'GeoIP.conf.md'
      - 'geoipupdate.md'
builds:
  - main: './cmd/geoipupdate'
    binary: 'geoipupdate'
    goarch:
      - '386'
      - 'amd64'
      - 'arm'
      - 'arm64'
    goos:
      - 'linux'
    hooks:
      post: 'make data BUILDDIR=. CONFFILE=/etc/GeoIP.conf DATADIR=/usr/share/GeoIP'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.defaultConfigFile=/etc/GeoIP.conf -X main.defaultDatabaseDirectory=/usr/share/GeoIP'
    env:
      - CGO_ENABLED=0
checksum:
  name_template: 'checksums-dpkg-rpm.txt'
nfpms:
  - vendor: 'MaxMind, Inc.'
    homepage: https://www.maxmind.com/
    maintainer: 'MaxMind, Inc. <support@maxmind.com>'
    description: Program to perform automatic updates of GeoIP2 and GeoIP Legacy binary databases.
    license: Apache 2.0 or MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    empty_folders:
      - /usr/share/GeoIP
    contents:
      - src: 'CHANGELOG.md'
        dst: '/usr/share/doc/geoipupdate/CHANGELOG.md'
      - src: 'LICENSE-APACHE'
        dst: '/usr/share/doc/geoipupdate/LICENSE-APACHE'
      - src: 'LICENSE-MIT'
        dst: '/usr/share/doc/geoipupdate/LICENSE-MIT'
      - src: 'README.md'
        dst: '/usr/share/doc/geoipupdate/README.md'
      - src: 'GeoIP.conf'
        dst: '/usr/share/doc/geoipupdate/GeoIP.conf'
      - src: 'GeoIP.conf.md'
        dst: '/usr/share/doc/geoipupdate/GeoIP.conf.md'
      - src: 'geoipupdate.md'
        dst: '/usr/share/doc/geoipupdate/geoipupdate.md'
      - src: 'GeoIP.conf'
        dst: '/etc/GeoIP.conf'
        type: config
release:
  # We disable the release as there is no way to disable the creation of
  # the archive version and we don't want to upload those. We also can
  # only do one release.
  disable: true
