project_name: 'geoipupdate'
archive:
  wrap_in_directory: true
  files:
    - 'CHANGELOG.md'
    - 'LICENSE-APACHE'
    - 'LICENSE-MIT'
    - 'README.md'
    - 'GeoIP.conf'
    - 'GeoIP.conf.md'
    - 'geoipupdate.md'
  format_overrides:
    - goos: windows
      format: zip
builds:
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - 'amd64'
  goos:
    - 'darwin'
  hooks:
    post: 'make data BUILDDIR=dist/darwin_amd64'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - '386'
  goos:
    - 'linux'
  hooks:
    post: 'make data BUILDDIR=dist/linux_386'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - 'amd64'
  goos:
    - 'linux'
  hooks:
    post: 'make data BUILDDIR=dist/linux_amd64'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - '386'
  goos:
    - 'windows'
  hooks:
    post: 'make data OS=Windows_NT BUILDDIR=dist/windows_386'
- main: './cmd/geoipupdate'
  binary: 'geoipupdate'
  goarch:
    - 'amd64'
  goos:
    - 'windows'
  hooks:
    post: 'make data OS=Windows_NT BUILDDIR=dist/windows_amd64'
checksum:
  name_template: 'checksums.txt'
