---
sudo: false
language: c
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
env: CFLAGS="-std=c99 -Wall -Wextra -Werror"
before_script:
  - ./bootstrap
  - ./configure
script:
  - make
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "E8Ka0sqeEhUzo/on3p3QRb67CzsfcYl7Rure2Zdi0L7fbePAXOkvMyrEPU6SUXguFRFgiexsQOPwXrESEi6sC+yJkm7VMoKJcFrPcXTu5y1SjGJRu+iyBqIpt3hzJBdU0bOzHzywf+096yobWP6ERf3Rx8jUoR92VhBajhePh9Q=\n"
